version: '3'

services:
  dmd:
    build:
      context: .
      platforms: 
        - "linux/amd64"
      args:
        - TARGET=dmd
  ldc:
    build:
      context: .
      args:
        - TARGET=ldc
    volumes:
      - ./app.d:/root/main/source/app.d
    command: bash -c "
      dub build --skip-registry=all --nodeps --build=release-nobounds &&
      ./main
      "
    