version: '3'

networks:
  no_out:
    name: no_out
    internal: true

services:
  dmd:
    build:
      context: .
      args:
        - TARGET=dmd
    volumes:
      - ./app.d:/judge/source/app.d
    networks:
      - no_out
    environment:
      - DFLAGS="-O -release -boundscheck=off"
    command: sh -c "dub build --skip-registry=all --nodeps --build=release-nobounds && ./judge"

  ldc:
    build:
      context: .
      args:
        - TARGET=ldc
    volumes:
      - ./app.d:/judge/source/app.d
    networks:
      - no_out
    command: sh -c "dub build --skip-registry=all --nodeps --build=release-nobounds && ./judge"
